### ISSUE TITLE
Bad legibility of tests that send TAB

### ISSUE THREAD

**Issue by sglebs** [andreptb/fitnesse-selenium-slim#8]
I use this:

```
| send keys | ${KEY_TAB} |
```

But the page reads like this:

```
| send keys | ? |
```

This makes the test cryptic to read. The user/reader can't figure out the intent. It is displaying the HOW instead of the WHAT. This violates Clean Code rules for tests, or Knuth's Literate Programming principles.

**Comment by andrealbinop** [comment]
To me a variable such as **${KEY_TAB}** by itself is somewhat cryptic. Anyhow, I see your point. Considering how [I've implemented](https://github.com/andreptb/fitnesse-selenium-slim/blob/master/src/main/java/com/github/andreptb/fitnesse/plugins/SeleniumPluginFeatureFactory.java), I didn't find a way to change what is rendered since ${KEY_TAB} variable is substituted by a unicode key that selenium will interpret. 

I'll come up with something for the next version, thanks!

**Comment by sglebs** [comment]
Please leave the current API as is and add an API sendSpecialKeys which interprets the high-level names, as you used to have: sendSpecialKeys("tab") ,  sendSpecialKeys("tab enter")

I presume that you suppress/ignore spaces in the example above, sending just TAB and ENTER without the SPACE in between, right?

**Comment by andrealbinop** [comment]
Hi @sglebs,
I've found a way to render ${KEY_XXX} variables in a "non-cryptic" way. Now the variable is rendered the same way you typed, but the Fixture will interpret the unicode value property. I did the trick by replacing:

``` html
${KEY_TAB}
```

With:

``` html
!-<span keycode="\uE004">${KEY_TAB}</span>-!
```

FitNesse renders **${KEY_TAB}** and in the fixture I'm able to leave only the keycode. Will that do?

**Comment by sglebs** [comment]
If I type ${KEY_TAB} and I see ${KEY_TAB} and it sends a TAB, that's fine. Is that what you mean?

I don't need to type or see !-<span keycode="\uE004">${KEY_TAB}</span>-! , right? That's you behind the scenes, right?

**Comment by andrealbinop** [comment]
Right
